### ISSUE TITLE
My task list

### ISSUE THREAD

**Issue by fmezou** [fmezou/my_sandbox#6]
- [x] Finish my changes
- [x] Push my commits to GitHub
- [x] Open a pull request
- [ ] A new item
